apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: shipping-service-rmq
  annotations: {}
  labels:
    app.kubernetes.io/part-of: shipping-service
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: worker
    app.kubernetes.io/component: run
    carto.run/workload-name: shipping-service
spec:
  name: rmq
  service:
    apiVersion: rabbitmq.com/v1beta1
    kind: RabbitmqCluster
    name: rmq-1
  workload:
    apiVersion: apps/v1
    kind: Deployment
    name: shipping-service
---
apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: shipping-service-config-server
  annotations: {}
  labels:
    app.kubernetes.io/part-of: shipping-service
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: worker
    app.kubernetes.io/component: run
    carto.run/workload-name: shipping-service
spec:
  name: config-server
  service:
    apiVersion: services.apps.tanzu.vmware.com/v1alpha1
    kind: ResourceClaim
    name: configserver-binding-compatible
  workload:
    apiVersion: apps/v1
    kind: Deployment
    name: shipping-service
---
apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: shipping-service-appsso-ca
  annotations: {}
  labels:
    app.kubernetes.io/part-of: shipping-service
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: worker
    app.kubernetes.io/component: run
    carto.run/workload-name: shipping-service
spec:
  name: appsso-ca
  service:
    apiVersion: services.apps.tanzu.vmware.com/v1alpha1
    kind: ResourceClaim
    name: gateway-ca-extra-binding-compatible
  workload:
    apiVersion: apps/v1
    kind: Deployment
    name: shipping-service

