apiVersion: apis.apps.tanzu.vmware.com/v1alpha1
kind: APIDescriptor
metadata:
  name: gateway
  annotations:
    autoscaling.knative.dev/min-scale: "1"
  labels:
    apis.apps.tanzu.vmware.com/register-api: "true"
    app.kubernetes.io/part-of: gateway
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: gateway
spec:
  type: openapi
  description: A set of API endpoints to manage the resources within the Spring Cloud Architecture app.
  system: sc-architecture-system
  owner: team-vmware-tanzu-se
  location:
    path: /v3/api-docs
    baseURL:
      ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: gateway

