apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: gateway-config-server
  annotations:
    autoscaling.knative.dev/min-scale: "1"
  labels:
    apis.apps.tanzu.vmware.com/register-api: "true"
    app.kubernetes.io/part-of: gateway
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: gateway
spec:
  name: config-server
  service:
    apiVersion: services.apps.tanzu.vmware.com/v1alpha1
    kind: ResourceClaim
    name: configserver-binding-compatible
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: gateway
---
apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: gateway-auth-client
  annotations:
    autoscaling.knative.dev/min-scale: "1"
  labels:
    apis.apps.tanzu.vmware.com/register-api: "true"
    app.kubernetes.io/part-of: gateway
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: gateway
spec:
  name: auth-client
  service:
    apiVersion: services.apps.tanzu.vmware.com/v1alpha1
    kind: ResourceClaim
    name: auth-client
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: gateway

