apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: order-service-rmq
  annotations:
    autoscaling.knative.dev/min-scale: "1"
  labels:
    app.kubernetes.io/part-of: order-service
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    networking.knative.dev/visibility: cluster-local
    app.kubernetes.io/component: run
    carto.run/workload-name: order-service
spec:
  name: rmq
  service:
    apiVersion: rabbitmq.com/v1beta1
    kind: RabbitmqCluster
    name: rmq-1
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: order-service
---
apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: order-service-db
  annotations:
    autoscaling.knative.dev/min-scale: "1"
  labels:
    app.kubernetes.io/part-of: order-service
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    networking.knative.dev/visibility: cluster-local
    app.kubernetes.io/component: run
    carto.run/workload-name: order-service
spec:
  name: db
  service:
    apiVersion: sql.tanzu.vmware.com/v1
    kind: Postgres
    name: postgres-1
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: order-service
---
apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: order-service-cache
  annotations:
    autoscaling.knative.dev/min-scale: "1"
  labels:
    app.kubernetes.io/part-of: order-service
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    networking.knative.dev/visibility: cluster-local
    app.kubernetes.io/component: run
    carto.run/workload-name: order-service
spec:
  name: cache
  service:
    apiVersion: services.apps.tanzu.vmware.com/v1alpha1
    kind: ResourceClaim
    name: gemfire-binding-compatible
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: order-service
---
apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: order-service-config-server
  annotations:
    autoscaling.knative.dev/min-scale: "1"
  labels:
    app.kubernetes.io/part-of: order-service
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    networking.knative.dev/visibility: cluster-local
    app.kubernetes.io/component: run
    carto.run/workload-name: order-service
spec:
  name: config-server
  service:
    apiVersion: services.apps.tanzu.vmware.com/v1alpha1
    kind: ResourceClaim
    name: configserver-binding-compatible
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: order-service
---
apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: order-service-auth-client
  annotations:
    autoscaling.knative.dev/min-scale: "1"
  labels:
    app.kubernetes.io/part-of: order-service
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    networking.knative.dev/visibility: cluster-local
    app.kubernetes.io/component: run
    carto.run/workload-name: order-service
spec:
  name: auth-client
  service:
    apiVersion: services.apps.tanzu.vmware.com/v1alpha1
    kind: ResourceClaim
    name: auth-client
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: order-service

